apiVersion: v2
name: automation-platform
version: 0.1.0
appVersion: "2.6"
description: Deploy Red Hat Ansible Automation Platform Operator and AAP custom resources on OpenShift.
type: application
keywords:
  - ansible
  - aap
  - openshift
  - operator
home: https://github.com/tonyreveal/automation_platform_helm
maintainers:
  - name: Tony Reveal
