global:
  namespace: aap
  commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

namespace:
  create: true
  name: "" # defaults to global.namespace
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "-20"

operator:
  enabled: true
  operatorGroup:
    create: true
    name: ansible-automation-platform-operator
    annotations:
      argocd.argoproj.io/sync-wave: "-10"
    # Set clusterScoped=true to omit targetNamespaces.
    clusterScoped: false
    targetNamespaces: [] # defaults to global.namespace when not clusterScoped
  subscription:
    name: ansible-automation-platform
    annotations:
      argocd.argoproj.io/sync-wave: "-5"
    channel: stable-2.6
    installPlanApproval: Automatic
    packageName: ansible-automation-platform-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace

secrets:
  enabled: true
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  externalDatabases:
    controller-db-secret:
      host: trrpostgres.texasroadracing.com
      port: "5432"
      database: automationcontroller
      username: automationcontroller
      password: automationcontroller
      sslmode: prefer
      type: unmanaged
    eda-db-secret:
      host: trrpostgres.texasroadracing.com
      port: "5432"
      database: automationeda
      username: automationeda
      password: automationeda
      sslmode: prefer
      type: unmanaged
    gateway-db-secret:
      host: trrpostgres.texasroadracing.com
      port: "5432"
      database: automationgateway
      username: automationgateway
      password: automationgateway
      sslmode: prefer
      type: unmanaged
    hub-db-secret:
      host: trrpostgres.texasroadracing.com
      port: "5432"
      database: automationhub
      username: automationhub
      password: automationhub
      sslmode: prefer
      type: unmanaged
    redis-secret:
      host: redis.texasroadracing.com
      port: "6379"
      password: redis

platform:
  enabled: true
  name: aap
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    app.kubernetes.io/managed-by: aap-operator
    app.kubernetes.io/name: aap
    app.kubernetes.io/operator-version: "2.6"
    app.kubernetes.io/part-of: aap
  spec:
    route_tls_termination_mechanism: Edge
    admin_password_secret: aap-controller-admin-password
    service_type: ClusterIP
    ingress_type: Route
    no_log: false
    image_pull_policy: Always
    hostname: aapextdb.apps.trrocp4.texasroadracing.com
    api:
      log_level: INFO
      replicas: 1
      route_host: aapextdb.apps.trrocp4.texasroadracing.com
    database:
      postgres_data_volume_init: false
      database_secret: gateway-db-secret
    redis_mode: cluster
    redis:
      replicas: 6
      # external: true
      # redis_secret: redis-secret
    hub:
      file_storage_storage_class: nfs-client
      redis_storage_class: nfs-client
      postgres_configuration_secret: hub-db-secret
    controller:
      postgres_configuration_secret: controller-db-secret
    eda:
      database:
        database_secret: eda-db-secret
    mcp:
      allow_write_operations: true
      disabled: false

consoleLink:
  enabled: true
  name: aap
  annotations: {}
  applicationMenu:
    section: Red Hat applications
  imageURL: "" # optional data:image/png;base64,...
  href: https://automationplatform.apps.trrocp4.texasroadracing.com/
  location: ApplicationMenu
  text: AAP
