---
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  generation: 1
  labels:
    app.kubernetes.io/managed-by: aap-operator
    app.kubernetes.io/name: aap
    app.kubernetes.io/operator-version: '2.6'
    app.kubernetes.io/part-of: aap
  name: aap
  namespace: automation-platform-external-db
spec:
  route_tls_termination_mechanism: Edge
  admin_password_secret: aap-controller-admin-password
  service_type: ClusterIP
  ingress_type: Route
  no_log: false
  image_pull_policy: Always
  hostname: aapextdb.apps.trrocp4.texasroadracing.com
  api:
    log_level: INFO
    replicas: 1
  route_host: aapextdb.apps.trrocp4.texasroadracing.com
  database:
    postgres_data_volume_init: false
    database_secret: gateway-db-secret
  redis_mode: cluster
  redis:
    replicas: 6
    # external: true
    # redis_secret: redis-secret
  hub:
    file_storage_storage_class: nfs-client
    redis_storage_class: nfs-client
    postgres_configuration_secret: hub-db-secret
  controller:
    postgres_configuration_secret: controller-db-secret
  eda:
    database:
      database_secret: eda-db-secret
  mcp:
    allow_write_operations: true
    disabled: false
...
