---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../operator/overlays/stable-2.6
  - ./secrets.yml
  - ./ansibleautomationplatform.yml
  - ./aap-console-link.yml

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

patches:
  - target:
      kind: Namespace
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-20"
  - target:
      kind: RoleBinding
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-15"
  - target:
      kind: OperatorGroup
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-10"
  - target:
      kind: Subscription
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-5"
  - target:
      kind: Secrets
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "0"
  - target:
      kind: AnsibleAutomationPlatform
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "5"
...
