---
apiVersion: v1
kind: Secret
metadata:
  name: controller-db-secret
  namespace: automation-platform-external-db
stringData:
  host: trrpostgres.texasroadracing.com
  port: "5432"
  database: automationcontroller
  username: automationcontroller
  password: automationcontroller
  sslmode: prefer
  type: unmanaged
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: eda-db-secret
  namespace: automation-platform-external-db
stringData:
  host: trrpostgres.texasroadracing.com
  port: "5432"
  database: automationeda
  username: automationeda
  password: automationeda
  sslmode: prefer
  type: unmanaged
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-db-secret
  namespace: automation-platform-external-db
stringData:
  host: trrpostgres.texasroadracing.com
  port: "5432"
  database: automationgateway
  username: automationgateway
  password: automationgateway
  sslmode: prefer
  type: unmanaged
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: hub-db-secret
  namespace: automation-platform-external-db
stringData:
  host: trrpostgres.texasroadracing.com
  port: "5432"
  database: automationhub
  username: automationhub
  password: automationhub
  sslmode: prefer
  type: unmanaged
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: automation-platform-external-db
stringData:
  host: redis.texasroadracing.com
  port: "6379"
  password: redis
type: Opaque
...
