{{- if .Values.secrets.enabled }}
{{- range $name, $secret := .Values.secrets.externalDatabases }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ include "automation-platform.namespace" $ }}
  labels:
{{- include "automation-platform.labels" $ | nindent 4 }}
  annotations:
{{- include "automation-platform.annotations" $ | nindent 4 }}
{{- with $.Values.secrets.annotations }}
{{- toYaml . | nindent 4 }}
{{- end }}
type: Opaque
stringData:
{{- range $key, $value := $secret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
